//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerivcoDemo.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public System.Guid MenuItemId { get; set; }
        public int CategoryId { get; set; }
        public string MenuItemCode { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDescription { get; set; }
        public string MenuItemImagePath { get; set; }
        public decimal MenuItemPrice { get; set; }
    }
}
